export const ORDERS_SERVICE = 'ORDERS_SERVICE';

export const PAYMENTS_SERVICE = 'PAYMENTS_SERVICE';

export const INVENTORY_SERVICE = 'INVENTORY_SERVICE';

export const ORDERS_STATUSES = {
  PROCESSING: 'PROCESSING',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  STOCK_CONFIRMED: 'STOCK_CONFIRMED',
  AWAITING_PAYMENT: 'AWAITING_PAYMENT',
  PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
  PAYMENT_FAILED: 'PAYMENT_COMPLETED',
};
